port = 3000
addr = "127.0.0.1"

[sources]
cat = "https://cat-fact.herokuapp.com/facts/random?animal_type=cat&amount=1"
dog = "https://dog-api.kinduff.com/api/facts?number=1"
# horse = "https://cat-fact.herokuapp.com/facts/random?animal_type=horse&amount=1"